name: Chitetsu train log 6h
on:
  workflow_dispatch:   # 手動実行も可能
  schedule:
    - cron: "0 19 * * *"   # JST 4時
    - cron: "0 23 * * *"    # JST 8時
    - cron: "0 5 * * *"    # JST 14時
    - cron: "0 10 * * *"   # JST 19時

jobs:
  run-logger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install jpholiday
        
      - name: Run train logger
        run: python train_logger_with_number.py

      - name: Upload CSV logs
        uses: actions/upload-artifact@v4
        with:
          name: train-log-csv
          path: csv/train_log_*.csv
